# name: /home/sdq/GitHub/guoyi/sparqling-queries/data/break/logical-forms-fixed/outputs/4.simplet5-epoch-19-train-loss-0.0348-val-loss-0.2246
name: T5Gate
class_name: T5ForConditionalGeneration
tokenizer_class: T5Tokenizer
tokenizer_name: T5Gate
# tokenizer_name: /home/sdq/GitHub/guoyi/sparqling-queries/data/break/logical-forms-fixed/outputs/4.simplet5-epoch-19-train-loss-0.0348-val-loss-0.2246
inner_params:
- encoder.block.6.layer.1.DenseReluDense.wi.weight
- encoder.block.6.layer.1.DenseReluDense.wo.weight
- encoder.block.7.layer.1.DenseReluDense.wi.weight
- encoder.block.7.layer.1.DenseReluDense.wo.weight
- encoder.block.8.layer.1.DenseReluDense.wi.weight
- encoder.block.8.layer.1.DenseReluDense.wo.weight
- encoder.block.9.layer.1.DenseReluDense.wi.weight
- encoder.block.9.layer.1.DenseReluDense.wo.weight
- encoder.block.10.layer.1.DenseReluDense.wi.weight
- encoder.block.10.layer.1.DenseReluDense.wo.weight
- encoder.block.11.layer.1.DenseReluDense.wi.weight
- encoder.block.11.layer.1.DenseReluDense.wo.weight
- decoder.block.6.layer.2.DenseReluDense.wi.weight
- decoder.block.6.layer.2.DenseReluDense.wo.weight
- decoder.block.7.layer.2.DenseReluDense.wi.weight
- decoder.block.7.layer.2.DenseReluDense.wo.weight
- decoder.block.8.layer.2.DenseReluDense.wi.weight
- decoder.block.8.layer.2.DenseReluDense.wo.weight
- decoder.block.9.layer.2.DenseReluDense.wi.weight
- decoder.block.9.layer.2.DenseReluDense.wo.weight
- decoder.block.10.layer.2.DenseReluDense.wi.weight
- decoder.block.10.layer.2.DenseReluDense.wo.weight
- decoder.block.11.layer.2.DenseReluDense.wi.weight
- decoder.block.11.layer.2.DenseReluDense.wo.weight
pt: null