name: /home/sdq/GitHub/guoyi/mend/datamodels/simplet5-epoch-7-train-loss-0.1483-val-loss-0.1631
class_name: T5ForConditionalGeneration
tokenizer_class: T5Tokenizer
tokenizer_name: /home/sdq/GitHub/guoyi/mend/datamodels/simplet5-epoch-7-train-loss-0.1483-val-loss-0.1631
inner_params:
- "encoder.block.9.layer.1.DenseReluDense.wi.weight"
- "encoder.block.9.layer.1.DenseReluDense.wo.weight"
- "encoder.block.10.layer.1.DenseReluDense.wi.weight"
- "encoder.block.10.layer.1.DenseReluDense.wo.weight"
- "encoder.block.11.layer.1.DenseReluDense.wi.weight"
- "encoder.block.11.layer.1.DenseReluDense.wo.weight"
- "decoder.block.9.layer.2.DenseReluDense.wi.weight"
- "decoder.block.9.layer.2.DenseReluDense.wo.weight"
- "decoder.block.10.layer.2.DenseReluDense.wi.weight"
- "decoder.block.10.layer.2.DenseReluDense.wo.weight"
- "decoder.block.11.layer.2.DenseReluDense.wi.weight"
- "decoder.block.11.layer.2.DenseReluDense.wo.weight"

pt: null